PHP 8 support
digbang/docker pull request #3
Opened 2021-02-18 17:24 UTC by marianofilipoff

2021-02-19 11:55 UTC, dpgover requested changes

2021-02-19 11:55 UTC, dpgover commented on php-dev/8.0/Dockerfile
> +LABEL maintainer="Dario Govergun <dgovergun@digbang.com>"
Me falta un maintainer...

2021-02-19 11:55 UTC, dpgover commented on php-dev/8.0/conf.d/docker-php-ext-opcache.ini
> +opcache.enable=1
Para dev no esta bueno que este habilitado por default.

2021-02-19 11:55 UTC, dpgover commented on php/8.0/Dockerfile
> +LABEL maintainer="Dario Govergun <dgovergun@digbang.com>"
Falta un maintainer

2021-02-19 11:55 UTC, dpgover commented on php/Dockerfile_8.0.template
> +LABEL maintainer="Dario Govergun <dgovergun@digbang.com>"
Falta un maintainer

2021-02-19 11:55 UTC, dpgover commented on php-dev/8.0/conf.d/docker-php-ext-opcache.ini
> +opcache.enable=1
Por otro lado... creo que deberias agregarlo tambien al que es no dev

2021-12-15 15:45 UTC, marianofilipoff commented on php-dev/8.0/conf.d/docker-php-ext-opcache.ini
> +opcache.enable=1
![image](https://user-images.githubusercontent.com/17851999/146217790-f722df57-dde5-405a-8ebf-21b0441c3bab.png)

Teniendo en cuenta estas variables:
```
opcache.revalidate_freq=0
opcache.validate_timestamps=1
```

Vale la pena tenerlo activo en desarrollo, y no afecta en nada.

Por otro lado, por que lo habilitaría en no-dev, si el Docker lo usamos solo en desarrollo?

2021-12-15 16:29 UTC, dpgover approved these changes

2021-12-15 16:30 UTC, dpgover commented on php-dev/8.0/conf.d/docker-php-ext-opcache.ini
> +opcache.enable=1
Tuve casos en los que tuve problemas con opcache activado. Pero tal vez eran mis pruebas raras del momento.
La idea del "no-dev" es que en algun momento podriamos usarlos en prod para deployar y mantener la infra... hoy no lo hacemos, mañana no se.

2021-12-15 16:43 UTC, riedelalejandro commented
🎅

2021-12-15 16:44 UTC, dpgover commented
> 🎅

😄

2021-12-15 17:34 UTC, marianofilipoff commented on php-dev/8.0/conf.d/docker-php-ext-opcache.ini
> +opcache.enable=1
@dpgover listo! Actualizado para no-dev, desde 7.2 en adelante, tal como habíamos aplicado los cambios en dev.
Lo único que sí, en prod lo habilité pero lo dejé con los settings por defecto, si encontramos algunas settings óptimas (cosa que veo medio subjetivo, depende del proyecto, etc) lo podemos tunear.

2022-06-27 15:07 UTC, merged